stages:
  - build
  - deploy

cache:
    paths:
        - dist/

build:
    stage: build
    script:
        - rm -rf node_modules
        - /usr/bin/pnpm install --no-frozen-lockfile
        - /usr/bin/pnpm run build
    interruptible: true
    rules:
        - if: $CI_COMMIT_BRANCH == "main"

deploy:
    stage: deploy
    script:
        - rm -rf /web/fuori-org/*
        - mv dist/* /web/fuori-org/
    interruptible: false
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
          when: manual
